### ISSUE TITLE
empty bed and .tsv file 

### ISSUE THREAD

**Issue by rezenman** [harvardinformatics/degenotate#41]
Hey,
Trying to run degenotate on a folder contacting a fasta file, 
Everything seems to work fine but I get an error at the end and my .bed and .tsv files are empty.
Any help will be appreciated!
Thanks

adding the output:

./degenotate/degenotate.py -s fasta_files/ -o annotated

Welcome to degenotate -- Degeneracy annotation for coding transcripts.
Version 1.2.2 released on June 2023
degenotate was developed by Timothy Sackton, Gregg Thomas
Website:       https://github.com/harvardinformatics/degenotate

The date and time at the start is:  08.26.2023 | 13:16:33
Using Python executable located at: /home/labs/bfreich/shaharr/project/conda_envs/degenotate/bin/python3.10
Using Python version:               3.10.12
The program was called as:          ./degenotate/degenotate.py -s fasta_files/ -o annotated

-----------------------------------------------------------------------------------------------------------------------------
INPUT/OUTPUT INFO:
Sequence directory:                   /home/labs/bfreich/shaharr/WGS2_NovaSeq_290323/degenotate/fasta_files
Output directory:                     annotated
Per-site degeneracy output:           annotated/degeneracy-all-sites.bed
Transcript count output:              annotated/transcript-counts.tsv
Log file:                             annotated.log
-----------------------------------------------------------------------------------------------------------------------------
OPTIONS INFO:
Option                                Current setting               Current action
-m                                    3                             Transcripts shorter than this length will be ignored by degnotate.
--quiet                               False                         Time, memory, and status info will be printed to the screen while degenotate is running. ------------------------------------------------------------------------------------------------------------------------------------------------------
Date        Time      Current step                                      Status                                  Elapsed time (s)    Step time (s) ------------------------------------------------------------------------------------------------------------------------------------------------------
08.26.2023  13:16:33  Reading CDS FASTA file(s)                         In progress...
08.26.2023  13:16:33  Reading CDS FASTA file(s)                         Success: 1 CDS read                     0.01327             0.00415
08.26.2023  13:16:33  Caclulating degeneracy per transcript             Processed 0 / 1 transcripts...
Traceback (most recent call last):
  File "/home/labs/bfreich/shaharr/WGS2_NovaSeq_290323/degenotate/./degenotate/degenotate.py", line 94, in <module>
    globs = degen.processCodons(globs)
  File "/home/labs/bfreich/shaharr/WGS2_NovaSeq_290323/degenotate/degenotate/degenotate_lib/degen.py", line 418, in processCodons
    OUT.writeBed(transcript_output['bed'], bedfile, globs['annotation'][transcript]['strand']);
KeyError: 's288c'

**Comment by tsackton** [comment]
Hi @rezenman, 

I can replicate this error on our test data, so it appears to be a bug in our code for processing a directory of transcript CDS files. Working on a fix now - stay tuned. Thanks for reporting.

Tim

**Comment by tsackton** [comment]
Hi @rezenman,

I've pushed an update to the 'develop' branch that fixes this issue in our test data. Can you please checkout this branch and see if it fixes the issue for you before I close this issue?

If you have installed degenotate via conda, you will need to clone a new version of degenotate for testing. Since your use does not require any dependencies, you can just do this via `git clone -b develop https://github.com/harvardinformatics/degenotate` and then you can cd to the degenotate directory and run with `python degenotate.py`.

Let us know if this works, or if you are still having issues.

Tim

**Comment by rezenman** [comment]
Hey, 
Thanks for the update. It works perfectly!
Shahar
