### ISSUE TITLE
How to extract 0-fold and 4-fold sites from VCF files, based on the output of degenotate

### ISSUE THREAD

**Issue by xiadawei123** [harvardinformatics/degenotate#49]
Hello, this is indeed a very powerful analysis software. I have a question for you: after mapping my resequencing samples to the genome.fa, I obtained a population-level VCF file. I successfully ran the command python degenotate.py -a genome.gff3 -g genome.fa -o output, which gave me the annotated degeneracy of sites at the genome level. Based on the output in the .bed file, I want to extract 0-fold and 4-fold sites from the VCF file using the start position of the site. However, I have some confusion regarding the "Start pos" tag.

First, does the "Start pos" refer to the position on the corresponding scaffold? For example, as shown below, the output indicates that the nucleotide at position 20365 on Ctg88 is A, but upon checking the sequence, I am sure that neither position 20365 nor 20366 on Ctg88 is A.

Second, using Ctg88 as an example, why does the sequence start from position 20365 and then continue consecutively downwards, ending at position 21143 before moving on to other scaffolds?

Thank you for your help.

![image](https://github.com/harvardinformatics/degenotate/assets/148743500/9735563b-009d-4c98-b264-a51a4b1c8be9)

**Comment by tsackton** [comment]
The nucleotide sequence is given in the coding frame, not the genome frame. It looks like this is a transcript on the reverse strand, so the base at position 20365 should be T (the reverse complement of A). I think that this might be incorrect in the docs, actually, thanks for pointing this out. 

The output also only reports positions in coding sequence (other positions do not, by definition, have degeneracy). That is why it ends, presumably there are no other coding sequences on this scaffold.

Note that the output is a bed file, so the coordinates are half-open, zero-based (the first position of a chromosome is recorded as start: 0, end: 1).

**Comment by xiadawei123** [comment]
> The nucleotide sequence is given in the coding frame, not the genome frame. It looks like this is a transcript on the reverse strand, so the base at position 20365 should be T (the reverse complement of A). I think that this might be incorrect in the docs, actually, thanks for pointing this out.
> 
> The output also only reports positions in coding sequence (other positions do not, by definition, have degeneracy). That is why it ends, presumably there are no other coding sequences on this scaffold.
> 
> Note that the output is a bed file, so the coordinates are half-open, zero-based (the first position of a chromosome is recorded as start: 0, end: 1).

Hi, thanks for your reply. I also suspect that the transcript might be the reverse complement of the genomic sequence. My output indicates that the position at 20366 is a 2-fold site. So, regardless of whether it is the forward or reverse sequence, can I consider the 20366th position in the genome to be a 2-fold site?

**Comment by tsackton** [comment]
Yes, that is correct
