### ISSUE TITLE
only pN pS calculated, no pvalues or direction

### ISSUE THREAD

**Issue by emgiles** [harvardinformatics/degenotate#50]
degenotate.py runs without issues to calculate pN pS values for a vcf including 2 outgroup individuals, 7 in-group individuals, and approx 24,000 transcripts; however, pvalues and subsequent columns in the mk output were not calculated. Is there a threshold of number of individuals to make these calculations, or are there formatting requirements for the vcf. Any help would be much appreciated.
Cheers

**Comment by gwct** [comment]
Hi,
Do you think you could share the exact command you used to run degenotate, as well as the text of log file?
Thanks!

**Comment by emgiles** [comment]
Hi Gregg
Thanks so much for the reply! Here is my command and log file
<https://www.dropbox.com/scl/fi/yieysjni26jzkk8hwdye3/1ss.log?rlkey=y6bx3gh0ebs61rqwkr6h4vp3q&dl=0>
:

nohup python /full_path/degenotate.py -a
/full_path/Scurria_scurra_annotation_v1_ch10_top10_longestisoform_gxfrun.gff
-g /full_path/HiRise/jasmine_nosemi_10chrm.fasta -u ../outgroup.txt -v
/full_path/scurra_viridula_zebrina_pileup_05jan2024_called_filtered2_fmiss50_allsites_10chrms_only10_scurra.vcf.gz
-o /full_path/degenotate_output/1ss -sfs --overwrite &



VCF has many scaffolds that I disregarded by only including the largest
scaffolds in the gff and fasta files.

**Comment by emgiles** [comment]
Also, the first few lines of mk.tsv look like this:
transcript	pN	pS	dN	dS	pval	odds_ni	dos	pn_af	ps_af
g11848.t1	34	7	0.0	0.0	NA	NA	NA	0.5,0.33,0.5,0.33,0.17,0.17,0.5,0.17,0.12,0.17,0.25,0.12,0.25,0.12,0.12,0.12,0.5,0.38,1.0,0.75,0.25,0.25,0.62,0.12,0.25,0.38,0.38,0.12,0.5,0.67,0.5,0.12,0.38,0.25,0.12,0.5,0.25,0.12,0.38,0.38,0.17,0.67,0.67,0.17	0.5,0.33,0.38,0.38,0.25,0.12,0.12,0.12,0.12,0.5,0.67
g11849.t1	5	3	0.0	0.0	NA	NA	NA	0.5,0.25,0.25,0.5,0.5	0.25,0.5,0.5
g11850.t1	0	0	0.0	0.0	NA	NA	NA		
g11851.t1	7	2	0.0	0.0	NA	NA	NA	0.25,0.5,0.5,0.25,0.25,0.25,0.5	0.5,0.25
g11852.t1	7	11	0.0	0.0	NA	NA	NA	0.17,0.5,0.17,0.83,0.33,0.33,0.17	0.17,0.33,0.17,0.33,0.83,0.33,0.33,0.33,0.33,0.33,0.83
g11853.t1	14	14	0.0	0.0	NA	NA	NA	0.33,0.17,0.17,0.67,0.17,0.17,0.17,0.33,0.17,0.5,0.25,0.5,0.33,0.5	0.17,0.33,0.5,0.33,0.33,0.25,0.12,0.17,0.17,0.17,0.83,0.83,0.67,0.5,0.17
g11854.t1	14	3	0.0	0.0	NA	NA	NA	0.33,0.17,0.5,0.33,0.17,0.17,0.17,0.17,0.17,0.33,0.17,0.17,0.33,0.33	0.17,0.5,0.33

**Comment by gwct** [comment]
Hmm, that is odd. 
One thing I notice in the log file is that you set the outgroups by using a text file (`outgroup.txt`), but in the info below the output samples are reported as paths to BAM files (`/path/scurra_PA_51.bam`, `/path/scurra_PA_52.bam`). Unless the column headers for your samples in the VCF file are also those paths to BAM files, this wouldn't work. The samples provided to `-u` should match the sample IDs in the VCF file. This would make some sense since it is only dN and dS that it isn't calculating. Though, even if this what is happening, we have an error check for it that should catch it, so something is up either way. Can you confirm that the headers in your VCF match what is provided in `outgroup.txt`?

Thanks!

**Comment by emgiles** [comment]
Hi Gregg,

Yes, the names of samples in the vcf are the full paths to the bams as
listed in the outgroup.txt.

**Comment by gwct** [comment]
Ok, thanks. That was the only obvious possibility I could see from the log file.  Is it possible that one or both outgroup samples are too closely related to the ingroup samples? This could mean its possible that an outgroup allele always also exists in the ingroup so no fixed differences are inferred.

One thing I would try is using only one outgroup sample and excluding the other with `-e` to see if that changes anything. If not, and you don't think the outgroups are too similar to the ingroups, then I think I'd have to see some of the VCF to try and figure it out.

**Comment by emgiles** [comment]
Yes! This could be the issue. This first try was within one species, the
outgroup samples are very closely related to the ingroup. I will try now
with another species, using the first as the outgroup. Thank you!

**Comment by emgiles** [comment]
Yep, dN, dS, pval, odds, and dos can now be calculated for some transcripts. This issue can be closed.

**Comment by emgiles** [comment]
Yep, it works now. #choosing outgroup wisely is important! Thanks

**Comment by gwct** [comment]
Great! One more note though: degenotate was designed assuming that the reference sample in the VCF is one of the ingroup samples. We added the `--no-fixed-in` to partially alleviate this, which skips sites if only the reference allele differs from all other ingroup samples. However, synonymous and non-synonymous changes are still determined based on the reference allele. So it might be ok if the reference is neither an ingroup nor outgroup sample as long as they are related as 

```((reference, ingroups),outgroups)```

 But the reference should definitely not be an outgroup sample.

**Comment by emgiles** [comment]
hmm... this does pose a problem as usually one creates a vcf using a
reference that is an outgroup so that many ingroups can be aligned to it.
So, I would need to align something even more distantly related to my
reference and add this to the vcf?

**Comment by emgiles** [comment]
Hi Gregg
I have one more question... does pN represent the ratio of non-synonymous
polymorphisms per non-nonsynonymous sites, or it represents raw counts of
nonsynonymous polymorphisms? I have the same doubt for pS....
Thanks

**Comment by tsackton** [comment]
Hi @emgiles 

pN and pS are the count of nonsynonymous and synonymous polymorphisms, respectively. To turn this into a ratio per site, you can divide the number of nonsynonymous or synonymous sites in the gene (also output by degenotate).

**Comment by emgiles** [comment]
Hi Gregg/ Tim
I have another (perhaps dumb) question. Can the MK tests be run if the outgroup is represented by only one sample? For example, if I retrieve a published genome, align it to the genome that all samples in my vcf were aligned to, and then add this vcf of one individual genome to my larger vcf, can I call that single individual as my outgroup? Basically is there a threshold for N of the outgroup?

Thanks!
Emily

**Comment by tsackton** [comment]
Yes, this is a common way to run the MK test, and should be totally fine.

**Comment by emgiles** [comment]
Great, thanks!
